# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the DEV branch
  push:
    branches: [ DEV ]
  pull_request:
    branches: [ DEV ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      ResourceGroupName: github-action-arm-rg
      ResourceGroupLocation: "westeurope"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git checkout DEV^

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ls -altr

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      ResourceGroupName: github-action-arm-rg
      ResourceGroupLocation: "westeurope"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ env.ResourceGroupName }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
              echo "Azure resource group created"
            fi

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: github-action-arm-rg
          # Specify the path or URL to the Azure Resource Manager template.
          template: $GITHUB_WORKSPACE/arm.json
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: Incremental
          # Specifies the name of the resource group deployment to create.
          # deploymentName: # optional
          # Supply deployment parameter values.
          # parameters: # optional
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
